### ISSUE TITLE
Instruction needed

### ISSUE THREAD

**Issue by iGrog** [lefred/mysql-component-uuid_v7#1]
Hi 
Thank you for you component. It seems to be right I need to add uuidv7 to mysql 8.

However, I'm not a C developer, could you please provide how to compile this component from the scratch? I tried to run `cmake` but got the following errors:

```
CMake Error at CMakeLists.txt:24 (DISABLE_MISSING_PROFILE_WARNING):
  Unknown CMake command "DISABLE_MISSING_PROFILE_WARNING".

CMake Error at CMakeLists.txt:28 (MYSQL_ADD_COMPONENT):
  Unknown CMake command "MYSQL_ADD_COMPONENT".
```
I'm missing some stuff. :) Could you please help?
Using Linux Ubuntu/Debian

**Comment by lefred** [comment]
Hi, sorry for the late reply, were you able to compile it ?

**Comment by iGrog** [comment]
Hi, not really.
But I solved this to create same function in MySQL SQL :)
